apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: cnrprod1725741033-team-78604
subjects:
  - kind: ServiceAccount
    name: cnrprod1725741033-team-78604  # Имя сервисного аккаунта
    namespace: cnrprod1725741033-team-78604
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
