apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: cnrprod1725741033-team-78604
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: ${{ secrets.DOCKER_USERNAME }}/avitoproject:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SERVER_ADDRESS
        - name: POSTGRES_CONN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_CONN
