apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: cnrprod1725741033-team-78604
type: Opaque
data:
  POSTGRES_CONN: cG9zdGdyZXM6Ly9jbnJwcm9kMTcyNTc0MTAzMy10ZWFtLTc4NjA0OmNucnByb2QxNzI1NzQxMDMzLXRlYW0tNzg2MDRAcmMxYi01eG1xeTZicTUwMWtsczRtLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9jbnJwcm9kMTcyNTc0MTAzMy10ZWFtLTc4NjA0
  POSTGRES_PASSWORD: Y25ycHJvZDE3MjU3NDEwMzMtdGVhbS03ODYwNA==
